CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'main') THEN
        CREATE SCHEMA main;
    END IF;
END $EF$;

CREATE TABLE main.website_info (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    website_url text NOT NULL,
    registered_at timestamp without time zone NOT NULL,
    monitoring_enabled boolean NOT NULL,
    last_checked_at timestamp without time zone NOT NULL,
    monitoring_interval_seconds integer NOT NULL,
    created_by bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    modified_by bigint,
    modified_at timestamp without time zone,
    CONSTRAINT "PK_website_info" PRIMARY KEY (id)
);

CREATE TABLE main.website_status_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    request_sent_at timestamp without time zone NOT NULL,
    website_info_id bigint NOT NULL,
    http_status_code integer NOT NULL,
    status_message text NOT NULL,
    is_up boolean NOT NULL,
    created_by bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    modified_by bigint,
    modified_at timestamp without time zone,
    CONSTRAINT "PK_website_status_history" PRIMARY KEY (id)
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241115173119_FullRefresh', '8.0.10');

COMMIT;

